BEGIN TRANSACTION;
DROP TABLE IF EXISTS "klassen";
CREATE TABLE IF NOT EXISTS "klassen" (
	"bezeichner"	TEXT NOT NULL,
	"jahrgang"	INTEGER,
	"zug"	TEXT,
	PRIMARY KEY("bezeichner")
);
DROP TABLE IF EXISTS "lehrer";
CREATE TABLE IF NOT EXISTS "lehrer" (
	"Kuerzel"	TEXT NOT NULL,
	"Vorname"	TEXT,
	"Nachname"	TEXT,
	PRIMARY KEY("Kuerzel")
);
DROP TABLE IF EXISTS "raeume";
CREATE TABLE IF NOT EXISTS "raeume" (
	"nummer"	TEXT NOT NULL,
	"etage"	INTEGER,
	PRIMARY KEY("nummer")
);
INSERT INTO "klassen" VALUES ('05a',5,'a');
INSERT INTO "klassen" VALUES ('05b',5,'b');
INSERT INTO "klassen" VALUES ('05c',5,'c');
INSERT INTO "klassen" VALUES ('05d',5,'d');
INSERT INTO "klassen" VALUES ('06a',6,'a');
INSERT INTO "klassen" VALUES ('06b',6,'b');
INSERT INTO "klassen" VALUES ('06c',6,'c');
INSERT INTO "klassen" VALUES ('06d',6,'d');
INSERT INTO "klassen" VALUES ('07a',7,'a');
INSERT INTO "klassen" VALUES ('07b',7,'b');
INSERT INTO "klassen" VALUES ('07c',7,'c');
INSERT INTO "klassen" VALUES ('07d',7,'d');
INSERT INTO "klassen" VALUES ('08a',8,'a');
INSERT INTO "klassen" VALUES ('08b',8,'b');
INSERT INTO "klassen" VALUES ('08c',8,'c');
INSERT INTO "klassen" VALUES ('08d',8,'d');
INSERT INTO "klassen" VALUES ('09a',9,'a');
INSERT INTO "klassen" VALUES ('09b',9,'b');
INSERT INTO "klassen" VALUES ('09c',9,'c');
INSERT INTO "klassen" VALUES ('09d',9,'d');
INSERT INTO "klassen" VALUES ('EFa',10,'a');
INSERT INTO "klassen" VALUES ('EFb',10,'b');
INSERT INTO "klassen" VALUES ('EFc',10,'c');
INSERT INTO "klassen" VALUES ('EFd',10,'d');
INSERT INTO "lehrer" VALUES ('bar','Barner','Angela');
INSERT INTO "lehrer" VALUES ('beh','Behlke','Christina');
INSERT INTO "lehrer" VALUES ('bhz','Buchholz-Neidhardt','Ilka');
INSERT INTO "lehrer" VALUES ('bmr','Burmeister','Felix');
INSERT INTO "lehrer" VALUES ('bod','Bodeck','Jörn');
INSERT INTO "lehrer" VALUES ('brs','Bruns','Maren');
INSERT INTO "lehrer" VALUES ('bru','Brune','Kerstin');
INSERT INTO "lehrer" VALUES ('buk','Bukarz','Julia Maria');
INSERT INTO "lehrer" VALUES ('buo','Bucko','Anna');
INSERT INTO "lehrer" VALUES ('det','Deters','Svenja');
INSERT INTO "lehrer" VALUES ('dfe','Diefenbach','Frank');
INSERT INTO "lehrer" VALUES ('dsl','Diesel','Stefan');
INSERT INTO "lehrer" VALUES ('est','Ester-Burschel','Barbara');
INSERT INTO "lehrer" VALUES ('fel','Felsch','Michael');
INSERT INTO "lehrer" VALUES ('fis','Fischer','Silke');
INSERT INTO "lehrer" VALUES ('frd','Freund','Sarah');
INSERT INTO "lehrer" VALUES ('fri','Fricke','Jan Dennis');
INSERT INTO "lehrer" VALUES ('ger','Gerke','Timo');
INSERT INTO "lehrer" VALUES ('gor','Gorges','Kristin');
INSERT INTO "lehrer" VALUES ('göt','Göttner','Wendy');
INSERT INTO "lehrer" VALUES ('grd','Gradowski von','Thomas');
INSERT INTO "lehrer" VALUES ('gru','Grube','Viktoria');
INSERT INTO "lehrer" VALUES ('gry','Generotzky','Constanze');
INSERT INTO "lehrer" VALUES ('hel','Held','Joachim');
INSERT INTO "lehrer" VALUES ('hob','Hoberg','Annika');
INSERT INTO "lehrer" VALUES ('hof','Hofmann','Jonas');
INSERT INTO "lehrer" VALUES ('hök','Höke','Sandra');
INSERT INTO "lehrer" VALUES ('hor','Hornig','Manuel');
INSERT INTO "lehrer" VALUES ('htn','Horstmann','Anne');
INSERT INTO "lehrer" VALUES ('imm','Immel','Bettina');
INSERT INTO "lehrer" VALUES ('jka','Jutka','Sabine');
INSERT INTO "lehrer" VALUES ('kah','Kahrau','Larissa');
INSERT INTO "lehrer" VALUES ('kch','Koch','Britta');
INSERT INTO "lehrer" VALUES ('khm','Kuhlmann','Florian');
INSERT INTO "lehrer" VALUES ('kop','Kropp','Elke');
INSERT INTO "lehrer" VALUES ('kpp','Knüppel','Christoph');
INSERT INTO "lehrer" VALUES ('kse','Krause','Kerstin');
INSERT INTO "lehrer" VALUES ('ksg','Klausing','Susanne');
INSERT INTO "lehrer" VALUES ('kth','Kreth','Maren');
INSERT INTO "lehrer" VALUES ('ldr','Linder','Sarah');
INSERT INTO "lehrer" VALUES ('leh','Lehmann','Daria');
INSERT INTO "lehrer" VALUES ('lin','Lindemann','Armin');
INSERT INTO "lehrer" VALUES ('lÜb','Lübbecke','Annika');
INSERT INTO "lehrer" VALUES ('mab','Maybaum','Regina');
INSERT INTO "lehrer" VALUES ('mei','Meise-Amthauer','Sylvia');
INSERT INTO "lehrer" VALUES ('mrg','Müller-Goerke','Ulrike');
INSERT INTO "lehrer" VALUES ('msl','Müller-Slanitz','Nadja');
INSERT INTO "lehrer" VALUES ('müh','Mühlenhoff','Paul');
INSERT INTO "lehrer" VALUES ('ngb','Neugebauer','Jonas');
INSERT INTO "lehrer" VALUES ('nid','Niedworok','Christian');
INSERT INTO "lehrer" VALUES ('nkp','Niekamp','Andrea');
INSERT INTO "lehrer" VALUES ('osm','Ostmeier','Tim');
INSERT INTO "lehrer" VALUES ('par','Paarmann','Oliver');
INSERT INTO "lehrer" VALUES ('pie','Pieper','Jennifer');
INSERT INTO "lehrer" VALUES ('plv','Pehlivan','Dervis');
INSERT INTO "lehrer" VALUES ('pör','Pörschke-Watt','Inga Kristin');
INSERT INTO "lehrer" VALUES ('pui','Puissant','Susanne');
INSERT INTO "lehrer" VALUES ('rak','Raach-Kallmer','Roswitha');
INSERT INTO "lehrer" VALUES ('rbg','Randenborgh van','Christian');
INSERT INTO "lehrer" VALUES ('rc','Reckelkamm','Bernd');
INSERT INTO "lehrer" VALUES ('rde','Rohde','Christine');
INSERT INTO "lehrer" VALUES ('rdt','Randt','Achim');
INSERT INTO "lehrer" VALUES ('rix','Rixe','Jeanette');
INSERT INTO "lehrer" VALUES ('rm','Redmann','Bastian');
INSERT INTO "lehrer" VALUES ('rup','Rupik','Karolina Beata');
INSERT INTO "lehrer" VALUES ('rüt','Rüthemann','Gunnar');
INSERT INTO "lehrer" VALUES ('sar','Sauer','Lisa');
INSERT INTO "lehrer" VALUES ('sat','Straetmanns','Florian');
INSERT INTO "lehrer" VALUES ('sdt','Schmidt','Moritz');
INSERT INTO "lehrer" VALUES ('sei','Seidenberg','Kristina');
INSERT INTO "lehrer" VALUES ('shz','Scholz','Nicole');
INSERT INTO "lehrer" VALUES ('sim','Simon-Edsen','Katja');
INSERT INTO "lehrer" VALUES ('slg','Stölting','Heike');
INSERT INTO "lehrer" VALUES ('smr','Schollmeier','David');
INSERT INTO "lehrer" VALUES ('snk','Schöneck','Gudrun-Verena');
INSERT INTO "lehrer" VALUES ('sön','Schöne','Claudia');
INSERT INTO "lehrer" VALUES ('spr','Sprenger','René');
INSERT INTO "lehrer" VALUES ('sra','Schramm','Saskia');
INSERT INTO "lehrer" VALUES ('stf','Steffen','Wiebke');
INSERT INTO "lehrer" VALUES ('stm','Strotherm','Janine');
INSERT INTO "lehrer" VALUES ('sto','Storz','Martin');
INSERT INTO "lehrer" VALUES ('str','Struwe','Simone');
INSERT INTO "lehrer" VALUES ('tes','Theessen','Johanna');
INSERT INTO "lehrer" VALUES ('the','Theeßen','Daniel');
INSERT INTO "lehrer" VALUES ('tsi','Tsironi','Paraskevi');
INSERT INTO "lehrer" VALUES ('ulr','Ulrich','Elias');
INSERT INTO "lehrer" VALUES ('vhs','Viehhauser','Werner');
INSERT INTO "lehrer" VALUES ('wab','Wabnitz','Sandra');
INSERT INTO "lehrer" VALUES ('wae','Wagner-Euteneier','Ina');
INSERT INTO "lehrer" VALUES ('wag','Wagner','Susanne');
INSERT INTO "lehrer" VALUES ('weh','Wehry','Martin');
INSERT INTO "lehrer" VALUES ('wel','Welland','Tanja');
INSERT INTO "lehrer" VALUES ('wen','Wendler','Jessica');
INSERT INTO "lehrer" VALUES ('wig','Wieling','Petra');
INSERT INTO "lehrer" VALUES ('wlm','Wiegelmann','Karen');
INSERT INTO "lehrer" VALUES ('wss','Weiß','David');
INSERT INTO "lehrer" VALUES ('zuc','Zucchini','Laura');
INSERT INTO "raeume" VALUES ('101',1);
INSERT INTO "raeume" VALUES ('102',1);
INSERT INTO "raeume" VALUES ('103',1);
INSERT INTO "raeume" VALUES ('104',1);
INSERT INTO "raeume" VALUES ('105',1);
INSERT INTO "raeume" VALUES ('106',1);
INSERT INTO "raeume" VALUES ('107',1);
INSERT INTO "raeume" VALUES ('108',1);
INSERT INTO "raeume" VALUES ('109',1);
INSERT INTO "raeume" VALUES ('110',1);
INSERT INTO "raeume" VALUES ('111',1);
INSERT INTO "raeume" VALUES ('112',1);
INSERT INTO "raeume" VALUES ('113',1);
INSERT INTO "raeume" VALUES ('114',1);
INSERT INTO "raeume" VALUES ('115',1);
INSERT INTO "raeume" VALUES ('116',1);
INSERT INTO "raeume" VALUES ('117',1);
INSERT INTO "raeume" VALUES ('118',1);
INSERT INTO "raeume" VALUES ('119',1);
INSERT INTO "raeume" VALUES ('120',1);
INSERT INTO "raeume" VALUES ('121',1);
INSERT INTO "raeume" VALUES ('122',1);
INSERT INTO "raeume" VALUES ('123',1);
INSERT INTO "raeume" VALUES ('124',1);
INSERT INTO "raeume" VALUES ('201',2);
INSERT INTO "raeume" VALUES ('202',2);
INSERT INTO "raeume" VALUES ('203',2);
INSERT INTO "raeume" VALUES ('204',2);
INSERT INTO "raeume" VALUES ('205',2);
INSERT INTO "raeume" VALUES ('206',2);
INSERT INTO "raeume" VALUES ('207',2);
INSERT INTO "raeume" VALUES ('208',2);
INSERT INTO "raeume" VALUES ('209',2);
INSERT INTO "raeume" VALUES ('210',2);
INSERT INTO "raeume" VALUES ('211',2);
INSERT INTO "raeume" VALUES ('212',2);
INSERT INTO "raeume" VALUES ('213',2);
INSERT INTO "raeume" VALUES ('214',2);
INSERT INTO "raeume" VALUES ('215',2);
INSERT INTO "raeume" VALUES ('216',2);
INSERT INTO "raeume" VALUES ('217',2);
INSERT INTO "raeume" VALUES ('218',2);
INSERT INTO "raeume" VALUES ('219',2);
INSERT INTO "raeume" VALUES ('220',2);
INSERT INTO "raeume" VALUES ('221',2);
INSERT INTO "raeume" VALUES ('222',2);
INSERT INTO "raeume" VALUES ('223',2);
INSERT INTO "raeume" VALUES ('224',2);
INSERT INTO "raeume" VALUES ('301',3);
INSERT INTO "raeume" VALUES ('302',3);
INSERT INTO "raeume" VALUES ('303',3);
INSERT INTO "raeume" VALUES ('304',3);
INSERT INTO "raeume" VALUES ('305',3);
INSERT INTO "raeume" VALUES ('306',3);
INSERT INTO "raeume" VALUES ('307',3);
INSERT INTO "raeume" VALUES ('308',3);
INSERT INTO "raeume" VALUES ('309',3);
INSERT INTO "raeume" VALUES ('310',3);
INSERT INTO "raeume" VALUES ('311',3);
INSERT INTO "raeume" VALUES ('312',3);
INSERT INTO "raeume" VALUES ('313',3);
INSERT INTO "raeume" VALUES ('314',3);
INSERT INTO "raeume" VALUES ('315',3);
INSERT INTO "raeume" VALUES ('316',3);
INSERT INTO "raeume" VALUES ('317',3);
INSERT INTO "raeume" VALUES ('318',3);
INSERT INTO "raeume" VALUES ('319',3);
INSERT INTO "raeume" VALUES ('320',3);
INSERT INTO "raeume" VALUES ('321',3);
INSERT INTO "raeume" VALUES ('322',3);
INSERT INTO "raeume" VALUES ('323',3);
INSERT INTO "raeume" VALUES ('324',3);
INSERT INTO "raeume" VALUES ('401',4);
INSERT INTO "raeume" VALUES ('402',4);
INSERT INTO "raeume" VALUES ('403',4);
INSERT INTO "raeume" VALUES ('404',4);
INSERT INTO "raeume" VALUES ('405',4);
INSERT INTO "raeume" VALUES ('406',4);
INSERT INTO "raeume" VALUES ('407',4);
INSERT INTO "raeume" VALUES ('408',4);
INSERT INTO "raeume" VALUES ('409',4);
INSERT INTO "raeume" VALUES ('410',4);
INSERT INTO "raeume" VALUES ('411',4);
INSERT INTO "raeume" VALUES ('412',4);
INSERT INTO "raeume" VALUES ('413',4);
INSERT INTO "raeume" VALUES ('414',4);
INSERT INTO "raeume" VALUES ('415',4);
INSERT INTO "raeume" VALUES ('416',4);
INSERT INTO "raeume" VALUES ('417',4);
INSERT INTO "raeume" VALUES ('418',4);
INSERT INTO "raeume" VALUES ('419',4);
INSERT INTO "raeume" VALUES ('420',4);
INSERT INTO "raeume" VALUES ('421',4);
INSERT INTO "raeume" VALUES ('422',4);
INSERT INTO "raeume" VALUES ('423',4);
INSERT INTO "raeume" VALUES ('424',4);
INSERT INTO "raeume" VALUES ('501',5);
INSERT INTO "raeume" VALUES ('033a',0);
INSERT INTO "raeume" VALUES ('033b',0);
INSERT INTO "raeume" VALUES ('025',0);
COMMIT;
